<?php
include("geoiploc.php");
/**
 * Implementation of hook_menu().
 */
function boomerang_menu() {
  $items = array();

  $items['admin/settings/boomerang'] = array(
    'title' => 'Boomerang',
    'description' => 'Configure Boomerang settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('boomerang_admin_settings'),
    'file' => 'boomerang.admin.inc',
    'access arguments' => array('administer boomerang'),
    'menu_name' => 'drubnub',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;

}

/**
 * Implementation of hook_perm().
 */
function boomerang_perm() {
  return array('administer boomerang', 'view boomerang results');
}

/**
 * Implementation of hook_init().
 */
function boomerang_init() {

  global $user;
	$set_ok = 0;
	$arr_roles = $user->roles;
	//print_r($arr_roles);
	foreach($arr_roles as $key => $ur){
//	if($ur=="Developer")
	$set_ok = 1;
	if($key==9)
	$set_ok = 1;
	}
	if($set_ok==1)
	{
  
  if (!variable_get('boomerang_tracking_enabled', TRUE)) {
    return;
  }

  // add boomerang script on all pages
  $library_path = libraries_get_path('boomerang');
  drupal_add_js($library_path .'/boomerang.js');
  drupal_add_js(drupal_get_path('module', 'boomerang') . '/boomerang.drupal.js');

  $path = $_GET['q'];
  $page_match = boomerang_match($path);

  $init['user_ip'] = ip_address();
  $ip_add =  ip_address();
  $init['ipaddress'] = $ip_add;
  $init['country']   = getCountryFromIP($ip_add);
  $country    = getCountryFromIP($ip_add);
   
  if (isset($_SERVER['HTTP_HOST'])) {
    $init['site_domain'] = '.'. preg_replace('`^www.`', '', $_SERVER['HTTP_HOST']);
  }
  if ($page_match) {
    // only set $images_path and $beacon_url if the page is not excluded
    global $base_url;
    $init['BW']['base_url'] = $base_url .'/'. $library_path . '/images/';
    $init['beacon_url'] = $base_url .'/beacon';
    // override $beacon_url if beacon is running externally
    if (variable_get('boomerang_external_beacon', '') && !module_exists('boomerang_external_beacon')) {
      $init['beacon_url'] = variable_get('boomerang_external_beacon', '');
    }
  }
  $init['RT']['cookie'] = 'BOOMR-RT';
  $init['RT']['cookie_exp'] = 120;
  $page_id = implode('/', arg());
  $json_init = json_encode($init);
  drupal_add_js("BOOMR.init($json_init);
    BOOMR.addVar('page_id', '$page_id');
    BOOMR.addVar('uid', '{$user->uid}');
    BOOMR.addVar('uname', '{$user->name}');
	BOOMR.addVar('ipaddress', '{$ip_add}');
	BOOMR.addVar('country', '{$country}');
    ", 'inline');

 }
}


/**
 * boomerang_match()
 *
 * Check the page past and see if it should have Boomerang loaded.
 *
 * @param $path
 *  the page of the page to check.
 *
 * @return
 *  0 - page should not include boomerang.
 *  1 - page should include boomerang.
 *  NULL - do not change page.
 */
function boomerang_match($path) {
  /**
   * Check to see if the page matches the current settings
   */
  $ignore = variable_get('boomerang_ignore', "node/add*\nnode/*/edit\nadmin*");

  //this section borrowed from secure_pages module
  if ($ignore) {    
    $regexp = '/^('. preg_replace(array('/(\r\n?|\n)/', '/\\\\\*/', '/(^|\|)\\\\<front\\\\>($|\|)/'), array('|', '.*', '\1'. preg_quote(variable_get('site_frontpage', 'node'), '/') .'\2'), preg_quote($ignore, '/')) .')$/';
    if (preg_match($regexp, $path)) {
      return 0;
    }
    else {
      return 1;
    }
  }
}

/**
 * Implementation of hook_footer().
 */
function boomerang_footer($main = 0) {
  if (user_access('view boomerang results')) {
    $footer .= '<div id="boomerang-results"></div>';
  }

  return $footer;
}

/**
 * Implementation of hook_preprocess_page().
 */
function boomerang_preprocess_page(&$variables) {
  global $user;
	$set_ok = 0;
	$arr_roles = $user->roles;
	//print_r($arr_roles);
	foreach($arr_roles as $key => $ur){
//	if($ur=="Developer")
	$set_ok = 1;
	if($key==9)
	$set_ok = 1;
	}
	if($set_ok==1)
	{

  $head = '';
  $footer = '';
  
  $head .= '<script type="text/javascript">var t_firstbyte=new Date().getTime();</script>' . "\n";

  $variables['head'] = $head . $variables['head'];

  $page_variables = array('scripts', 'styles');

  foreach ($page_variables as $page_variable) {
    $variables[$page_variable] = '<script type="text/javascript">var t_' . $page_variable . 'Start=new Date().getTime();</script>' . $variables[$page_variable] . '<script type="text/javascript">var t_' . $page_variable . 'End=new Date().getTime();</script>';
    $footer_js[] = 'BOOMR.plugins.RT.setTimer("h_' . $page_variable . '", t_' . $page_variable . 'End - t_' . $page_variable . 'Start);';
  }

  $footer_js[] = 'BOOMR.plugins.RT.startTimer("t_page", t_firstbyte);';

  $variables['footer'] =  $variables['footer'] . '<script type="text/javascript">' . implode('', $footer_js) .  '</script>';
  }
}
